[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[browser]
gatherUsageStats = false

[logger]
level = "error"

showWarningOnDirectExecution = false
showErrorDetails = false
toobarMode="viewer"

[server]
port = 5005